/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BuyOrders: typeof import('./components/BuyOrders.vue')['default']
    LastPrice: typeof import('./components/LastPrice.vue')['default']
    OrderBook: typeof import('./components/OrderBook.vue')['default']
    SellOrders: typeof import('./components/SellOrders.vue')['default']
    SvgIcon: typeof import('./components/common/SvgIcon.vue')['default']
    TestConnect: typeof import('./components/common/TestConnect.vue')['default']
  }
}
